### ISSUE TITLE
Contradiction between suggested content of my.cnf file

### ISSUE THREAD

**Issue by saurabh2804** [frappe/frappe_io#119]
[Tutorial says we are supposed to add following to my.cnf file:](https://frappe.io/docs/user/en/tutorial/setting-up-the-site)

```
[mysqld]
innodb-file-format=barracuda
innodb-file-per-table=1
innodb-large-prefix=1
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[mysql]
default-character-set = utf8mb4
```
However, the [Hitchhiker's guide to installing Frappe](https://github.com/frappe/frappe/wiki/The-Hitchhiker's-Guide-to-Installing-Frapp%C3%A9-on-Linux-OS) says:

```
[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[mysql]
default-character-set = utf8mb4
```
Following the Hitchhiker's guide worked well while following the tutorial instruction caused my mariaDB server to not start.
I am on Linux mint 19.

**Comment by georgreen** [comment]
Intresting, the tutorial version worked fine for me. I'm on macos though.
