### ISSUE TITLE
[Question] Tutorial image for Desk UI is misleading, under the start section.

### ISSUE THREAD

**Issue by georgreen** [frappe/frappe_io#147]
What the tutorial suggests I should see:
<img width="1196" alt="Screenshot 2019-03-31 at 20 24 20" src="https://user-images.githubusercontent.com/17669596/55292408-3867dd00-53f3-11e9-98bb-529cadb1609b.png">

What actually came up:

<img width="1675" alt="Screenshot 2019-03-31 at 20 30 12" src="https://user-images.githubusercontent.com/17669596/55292443-d360b700-53f3-11e9-91f3-6c8bcfa42944.png">

I follwed the tutorial sequentially, I only installed the libray app on one site. I'm supprised that my results don't match what is expected. I'm I missing something?

**Comment by ddavidebor** [comment]
Thank you for your issue @georgreen 
This is simply a case of the Desk being updated.

I will take charge of updating this documentation

**Comment by ddavidebor** [comment]
Most of the screenshot have been updated for version 13
