### ISSUE TITLE
Images on page `customize-erpnext/custom-doctype` are not available

### ISSUE THREAD

**Issue by wowkin2** [frappe/frappe_io#19]
On this page:
https://frappe.github.io/erpnext/user/manual/en/customize-erpnext/custom-doctype
following images are not available:
https://frappe.github.io/erpnext/assets/img/setup/customize/doctype-all-fields.png
https://frappe.github.io/erpnext/assets/img/setup/customize/doctype-permissions.png
https://frappe.github.io/erpnext/assets/img/setup/customize/doctype-list-view.png
https://frappe.github.io/erpnext/assets/img/setup/customize/doctype-book-added.png

**Comment by wowkin2** [comment]
Same thing here:
http://frappe.github.io/erpnext/user/manual/en/fleet_management/

**Comment by ddavidebor** [comment]
Thank you closing in favour of #282
