### ISSUE TITLE
Broken link in frappe documentation

### ISSUE THREAD

**Issue by JenishaJayaraj** [frappe/frappe_io#212]
On clicking Meta, the link is not working in https://frappe.io/docs/user/en/understanding-doctypes

**Comment by clarkejj** [comment]
Submit fix https://github.com/frappe/frappe_io/pull/217

**Comment by JenishaJayaraj** [comment]
Thanks for fixing it, is it possible to add a link to it, as it is given as Learn more about Meta

**Comment by ddavidebor** [comment]
@JenishaJayaraj thank you, i am closing in favour of #227
