### ISSUE TITLE
Getting Error Code 404 -In the side bar for the link Create Frappe App

### ISSUE THREAD

**Issue by abhinav-goyall** [frappe/frappe_io#225]
While i was going through frappe framework , i encountered a 404 error code for the below link.

Link:

https://frappe.io/docs/user/en/create-frappe-app
![404-error](https://user-images.githubusercontent.com/47552229/69422058-bbee8980-0d48-11ea-8072-c3063574cf4f.PNG)

**Comment by abhinav-goyall** [comment]
please comment

**Comment by ddavidebor** [comment]
Thank you @abhinav-goyall  for your issue and please excuse everyone for the disregard with which it was considered

I am closing in favour of #227 where all broken links will be addressed
