### ISSUE TITLE
Broken link - https://frappe.io/docs/user/en/create-frappe-app

### ISSUE THREAD

**Issue by clarkejj** [frappe/frappe_io#227]
Re this user report https://discuss.erpnext.com/t/broken-link-https-frappe-io-docs-user-en-create-frappe-app/55528

In the online docs, in the left sidebar menu here https://frappe.io/docs/user/en, the 'Creating a Frappe App' menu item links to here https://frappe.io/docs/user/en/create-frappe-app

But that link reference results in a 404 not found since create-frappe-app destination cannot be found here:

https://github.com/frappe/frappe_io/tree/master/frappe_io/www/docs/user/en

The question is where is create-frappe-app or has the file been deliberately deleted?

That will determine how the left menu will need to be edited
https://github.com/frappe/frappe_io/blob/master/frappe_io/www/docs/_sidebar.json

**Comment by FHenry** [comment]
Same to me. As I'm interested into frappe framework and the open source message deliver on frappe introduction pages, I'm wondering. 
The frappe framework is complex and if documentation are no more available that mean we have to read code to work with it. It's possible but really time and ressource consuming but hard way may be the better way...

**Comment by ddavidebor** [comment]
Hello @clarkejj thank you for your issue. I have opened a master issue #282 where I will take care 
of all the broken links.

Some help is needed in improving the documentation. I'm part of the community and decided to take charge of the issues cause I was annoyed the lack of work on the documentation.

If you can in any way contribute it would be very welcome

**Comment by clarkejj** [comment]
Thanks for jumping in with this initiative Davide.  The community succeeds thanks to folks like you...

**Comment by ddavidebor** [comment]
Getting annoyed as f*** is a powerful motivator!
