### ISSUE TITLE
Frappe Docs : Reporting Page Broken.

### ISSUE THREAD

**Issue by aaimaawebs** [frappe/frappe_io#23]
Hi,

As I was learning with the help of docs, more about Frappe & Codes. I noticed some of the pages doesn't have images also some of the page layouts are broken. When I reached to Github Repository of those docs, found everything to be correct.

While generating the page, no header and footer are going to render there.

Broken Page Link: [https://frappe.io/docs/user/en/guides/portal-development/generators](https://frappe.io/docs/user/en/guides/portal-development/generators) and
Github Repo MarkDown Link are: https://github.com/frappe/frappe_io/blob/master/frappe_io/www/docs/user/en/guides/portal-development/generators.md

**Comment by ddavidebor** [comment]
Thank you, closing in favour of #282
