### ISSUE TITLE
Guide for custom Social Login Key

### ISSUE THREAD

**Issue by MarekPikula** [frappe/frappe_io#257]
It would be nice to have a guide for setting up custom Social Login. Currently there is only a guide for the most common providers.

In order to set up self-hosted NextCloud as a provider I needed to look through very incomplete documentation, some loosely connected discussions and GitHub issues as well as code itself, to understand what's going on. It shouldn't be required to read the code in order to set this up.

I'll be working on better NextCloud integration shortly, so I may write something. I'm leaving this issue for future, until I write it, so that others can see that someone actually got it working.

**Comment by ddavidebor** [comment]
Hello @MarekPikula I am taking charge of fixing the documentation

Would you be willing to write down a quick tutorial on how to set up the social login you had issues with? #214  already includes some work
