### ISSUE TITLE
frappe.io certificate expired March 9, 2020. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by clarkejj** [frappe/frappe_io#265]
Re the Developer Docs hosted here https://frappe.io/docs

Chrome and Firefox just now report this:

Websites prove their identity via certificates, which are valid for a set time period. **The certificate for frappe.io expired on March 9, 2020.**

Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by ddavidebor** [comment]
This issue has been already addressed it seems 
closing for now
