### ISSUE TITLE
Move documentation in the frappe repo

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_io#281]
I'd recommend you move the documentation inside the frappe repo so that:

1. the documentation changes track the code changes
2. people who do PR can update the documentation without getting crazy
3. simple checks can be implemented to enforce it

I have been working on frappe for months and never saw this repo

**Comment by revant** [comment]
It was part of frappe repo

https://github.com/frappe/frappe/tree/v10.0.0/frappe/docs

at v10.0.0 the size of `docs` directory was 9.7MB

if (n) languages are added docs will become 9.7(n) MB.

assuming 9.7 to be size of docs even in v11/ v12/ v13(develop)

git clone will take some time in bare metal install

docker image size will increase, or during image creation `docs` directory needs to be deleted

**Comment by ddavidebor** [comment]
I will scratch my head and think about it. A submodule could be an option. Or a cleanup of all assets unrelated to the documentation (ie the main website assets) may be sufficient. 

But it's not 9.7(n), translated docs contain more or less the same media. 

Honestly, the juicy part of the documentation should only be PNG images, it's possible size will not be an issue after some cleanup.

We'll see. For now eventually moving the repo is a bit down the line, much to do first.

**Comment by ddavidebor** [comment]
Further discussion related to #296

**Comment by ddavidebor** [comment]
Closed in favour of https://github.com/frappe/frappe_docs/issues/74
