### ISSUE TITLE
Document building procedure and implement a CI

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_io#283]

**Comment by ddavidebor** [comment]
OH GOD THIS WHOLE THING IS A FRAPPE APP
Can't use travis cause local build options are 💩 
Can't just build it the old fashioned way cause I would loose my sanity

Need either Drone CI or Wercker CI and get them to build a whole frappe environment but we have the issue that the docker build requires human interaction when installing an app as it asks for the MySQL password

@revant do you think it's possible to get the developer environment in docker to take the MySQL password '123' automatically?

**Comment by ddavidebor** [comment]
Ugh we would also need to automate the first login where it asks you to input country and currency, as well as the admin password prompt

**Comment by revant** [comment]
> Ugh we would also need to automate the first login where it asks you to input country and currency, as well as the admin password prompt

Just a thought,

complete a wizard and site locally.
backup to `.sql`
patch `.sql` during CI / "before_start"

Drawbacks:
.sql will become outdated, either need to create new sql periodically or do `migrate` as part of ci startup scripts

**Comment by revant** [comment]
> do you think it's possible to get the developer environment in docker to take the MySQL password '123' automatically?

It can be passed as cli param

```sh
bench new-site docs.localhost --mariadb-root-password 123 --admin-password admin
```

**Comment by ddavidebor** [comment]
> > Ugh we would also need to automate the first login where it asks you to input country and currency, as well as the admin password prompt
> 
> Just a thought,
> 
> 1. complete site creation and the wizard locally.
> 2. backup to `.sql`
> 3. patch `.sql` during CI / "before_start"
> 
> Drawbacks:
> .sql will become outdated, either need to create new sql periodically or do `migrate` as part of ci startup scripts

I like it!



> > do you think it's possible to get the developer environment in docker to take the MySQL password '123' automatically?
> 
> It can be passed as cli param
> 
> ```shell
> bench new-site docs.localhost --mariadb-root-password 123 --admin-password admin
> ```

Thank you, I will also add it to the docker documentation!

**Comment by ddavidebor** [comment]
Apparently Wercker is kinda dead after it's acquisition by Oracle so it's either drone-ci or drone-ci... Which it's the best CI anyway so no worries there.

**Comment by ddavidebor** [comment]
Closed in favour of https://github.com/frappe/frappe_docs/issues/74
