### ISSUE TITLE
Cleaning stale branches

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_io#284]
@rmehta these branches are yours are they still useful or can they be cleaned up?

![Screenshot 2020-04-17 at 15 53 11](https://user-images.githubusercontent.com/9055742/79582422-a39a5500-80c3-11ea-8656-5ef963eb3895.png)

**Comment by ddavidebor** [comment]
same for these two branches:

![Screenshot 2020-04-17 at 15 54 31](https://user-images.githubusercontent.com/9055742/79582526-c88ec800-80c3-11ea-962b-75a61b10b194.png)
![Screenshot 2020-04-17 at 15 54 34](https://user-images.githubusercontent.com/9055742/79582530-caf12200-80c3-11ea-802b-72f212c05767.png)

@netchampfaris @surajshetty3416

**Comment by rmehta** [comment]
Deleted my branches!

**Comment by ddavidebor** [comment]
@rmehta you mean delete?

**Comment by ddavidebor** [comment]
@rmehta ok thanks!

**Comment by surajshetty3416** [comment]
@ddavidebor Cleared other branches as well.

**Comment by ddavidebor** [comment]
Closed in favour of https://github.com/frappe/frappe_docs/issues/74
