### ISSUE TITLE
Add updated feature list

### ISSUE THREAD

**Issue by ddavidebor** [frappe/frappe_io#289]
https://discuss.erpnext.com/t/frappe-does-not-have-a-feature-list/60455

**Comment by revant** [comment]
9 cards listed here

https://github.com/frappe/frappe_io/blob/master/frappe_io/www/frappe/index.html

**Comment by ddavidebor** [comment]
@revant thank you

**Comment by ddavidebor** [comment]
Closed in favour of https://github.com/frappe/frappe_docs/issues/74
