### ISSUE TITLE
Issue in Scheduled Tasks chapter (Chap-18) of tutorial

### ISSUE THREAD

**Issue by ni8mr** [frappe/frappe_io#7]
There is an **importError** while running the **tasks.py** defined in this chapter. 
 **datediff** and **format_date** can't be imported. 

 As **scheduler is disabled** while creating new-site, can i see the actual output of **tasks.py**? or how can i check the output of scheduler? 

 My tasks.py is in-

```
apps/library_management/library_management/tasks.py
```

**Comment by ddavidebor** [comment]
This is very old, closing
