### ISSUE TITLE
Bug: Accessing the blog returns sever error

### ISSUE THREAD

**Issue by strixaluco** [frappe/frappe_io#9]
I was checking the [official blog](https://frappe.io/blog) from time to time, but today it was impossible due to this server error:
> Server Error
> 
> Traceback (innermost last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
>     response = frappe.website.render.render(request.path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 40, in render
>     data = render_page(path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 107, in render_page
>     return build(path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 114, in build
>     return build_page(path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 127, in build_page
>     context = get_context(path)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 16, in get_context
>     context = build_context(context)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 54, in build_context
>     ret = module.get_context(context)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/templates/pages/list.py", line 22, in get_context
>     context.update(get(**frappe.local.form_dict))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/templates/pages/list.py", line 58, in get
>     set_route(new_context)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/templates/pages/list.py", line 73, in set_route
>     context.route = context.doc.get_route()
>  TypeError: 'NoneType' object is not callable

Tested on Firefox 38.7.1 ESR and Chromium 49.0.2623.108

**Comment by rmehta** [comment]
@strixaluco fixed. Thanks for reporting!

**Comment by strixaluco** [comment]
No problem, thanks for fixing.
